# Simple workflow for deploying static content to GitHub Pages
name: Revisar proyecto web

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  

jobs:
  primer_job: 
    runs-on: unbuntu-latest
    steps: 
      - name: Revisar archivos antes 
        run: ls
        
